version: '3.8'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=lambda,s3
    ports:
      - '4566-4583:4566-4583'
    volumes:
      - "${TEMPDIR:-/tmp/localstack}:/tmp/localstack"
      - /var/run/docker.sock:/var/run/docker.sock
      - ./aws:/etc/localstack/init/ready.d
    networks:
      - dev-network

  minio-s3:
    image: minio/minio:RELEASE.2022-10-24T18-35-07Z
    container_name: minio
    command: gateway s3 http://localstack:4566 --console-address :9001
    restart: always
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - dev-network
    links:
      - localstack

networks:
  dev-network:
